#include "FactoryTest.h"
#include "PinDefinitions.h"

FactoryTest::FactoryTest(Adafruit_SSD1306&d,Adafruit_NeoPixel&p):display(d),pixels(p){}
void FactoryTest::screen(const char*a,const char*b,const char*c,const char*d){display.clearDisplay();text.setCursor(0,14);text.print(a);text.setCursor(0,30);text.print(b);text.setCursor(0,46);text.print(c);text.setCursor(0,62);text.print(d);display.display();}
void FactoryTest::waitRelease(){while(!digitalRead(KUMITATE_PIN_SW1)||!digitalRead(KUMITATE_PIN_SW2)||!digitalRead(KUMITATE_PIN_SW3)||!digitalRead(KUMITATE_PIN_SW4))delay(5);delay(35);}
bool FactoryTest::waitButton(uint8_t pin,uint32_t timeout){waitRelease();uint32_t start=millis();while(!timeout||millis()-start<timeout){if(!digitalRead(pin)){delay(25);if(!digitalRead(pin)){while(!digitalRead(pin))delay(5);delay(25);return true;}}}return false;}
FactoryTest::Choice FactoryTest::ask(const char*item,const char*detail){screen(item,detail,"1:正常 2:異常","3:省略");waitRelease();for(;;){if(!digitalRead(KUMITATE_PIN_SW1)){while(!digitalRead(KUMITATE_PIN_SW1))delay(5);delay(25);return CHOICE_OK;}if(!digitalRead(KUMITATE_PIN_SW2)){while(!digitalRead(KUMITATE_PIN_SW2))delay(5);delay(25);return CHOICE_NG;}if(!digitalRead(KUMITATE_PIN_SW3)){while(!digitalRead(KUMITATE_PIN_SW3))delay(5);delay(25);return CHOICE_SKIP;}}}
void FactoryTest::record(const char*item,Choice v){if(v==CHOICE_OK){passCount++;Serial.printf("[PASS] %s\n",item);}else if(v==CHOICE_NG){failCount++;Serial.printf("[FAIL] %s\n",item);}else{skipCount++;Serial.printf("[SKIP] %s\n",item);}}
void FactoryTest::begin(){text.begin(display);text.setFont(u8g2_font_unifont_t_japanese3);text.setForegroundColor(SSD1306_WHITE);runAll();}
void FactoryTest::update(){if(finished&&!digitalRead(KUMITATE_PIN_SW4)){while(!digitalRead(KUMITATE_PIN_SW4))delay(5);delay(30);runAll();}}
void FactoryTest::runAll(){finished=false;passCount=failCount=skipCount=0;screen("工場検査","","","SW1:開始");waitButton(KUMITATE_PIN_SW1);testOled();testLed();testBuzzer();testRgb();testSwitches();testLoopback();summary();finished=true;}
void FactoryTest::testOled(){screen("OLED検査","画面を塗ります","","見てください");delay(400);display.clearDisplay();for(int y=0;y<64;y++){display.drawFastHLine(0,y,128,SSD1306_WHITE);display.display();delay(20);}delay(700);for(int y=63;y>=0;y--){display.drawFastHLine(0,y,128,SSD1306_BLACK);display.display();delay(20);}record("OLED",ask("OLED表示","塗り消し正常？"));}
void FactoryTest::testLed(){screen("青LED検査","3回点滅します","","D8を見る");pinMode(KUMITATE_PIN_LED,OUTPUT);for(int i=0;i<3;i++){digitalWrite(KUMITATE_PIN_LED,HIGH);delay(350);digitalWrite(KUMITATE_PIN_LED,LOW);delay(250);}record("BLUE LED",ask("青LED D8","3回点滅した？"));}
void FactoryTest::testBuzzer(){screen("ブザー検査","周波数スイープ","300Hz - 3500Hz","音を聞く");for(int c=0;c<2;c++){for(int f=300;f<=3500;f+=40){tone(KUMITATE_PIN_BUZZER,f);delay(6);}for(int f=3500;f>=300;f-=40){tone(KUMITATE_PIN_BUZZER,f);delay(6);}}noTone(KUMITATE_PIN_BUZZER);record("BUZZER",ask("ブザー BZ1","音は正常？"));}
void FactoryTest::testRgb(){screen("RGB LED検査","赤 緑 青 白","","4個を見る");uint32_t colors[]={pixels.Color(255,0,0),pixels.Color(0,255,0),pixels.Color(0,0,255),pixels.Color(255,255,255)};for(uint32_t c:colors){pixels.fill(c);pixels.show();delay(800);}pixels.clear();pixels.show();record("RGB LED",ask("RGB LED D1-D4","色と4灯 正常？"));}
void FactoryTest::testSwitches(){const char*names[]={"SW1","SW2","SW3","SW4"};for(int i=0;i<4;i++){pixels.clear();pixels.setPixelColor(i,pixels.Color(255,255,255));pixels.show();char prompt[32];snprintf(prompt,sizeof(prompt),"%sを押す",names[i]);screen("スイッチ検査",prompt,"待機中...","15秒で終了");bool good=waitButton(KUMITATE_SWITCH_PINS[i],15000);good?passCount++:failCount++;pixels.clear();pixels.setPixelColor(i,good?pixels.Color(0,255,0):pixels.Color(255,0,0));pixels.show();screen(good?"スイッチ正常":"スイッチ異常",names[i]);delay(500);}pixels.clear();pixels.show();}
bool FactoryTest::driveRead(uint8_t out,uint8_t in,uint8_t level){pinMode(out,OUTPUT);digitalWrite(out,level);pinMode(in,INPUT_PULLUP);delay(3);return digitalRead(in)==level;}
bool FactoryTest::pairTest(uint8_t a,uint8_t b){bool good=driveRead(a,b,LOW)&&driveRead(a,b,HIGH)&&driveRead(b,a,LOW)&&driveRead(b,a,HIGH);pinMode(a,INPUT);pinMode(b,INPUT);return good;}
void FactoryTest::testLoopback(){screen("GPIO折返し検査","J4: 4-5 と 6-7","SW1:検査","SW3:省略");waitRelease();while(digitalRead(KUMITATE_PIN_SW1)&&digitalRead(KUMITATE_PIN_SW3))delay(5);if(!digitalRead(KUMITATE_PIN_SW3)){while(!digitalRead(KUMITATE_PIN_SW3))delay(5);skipCount++;return;}while(!digitalRead(KUMITATE_PIN_SW1))delay(5);bool a=pairTest(KUMITATE_PIN_EXT4,KUMITATE_PIN_EXT5),b=pairTest(KUMITATE_PIN_EXT6,KUMITATE_PIN_EXT7);a?passCount++:failCount++;b?passCount++:failCount++;screen(a&&b?"折返し 正常":"折返し 異常",a?"GPIO4-5:正常":"GPIO4-5:異常",b?"GPIO6-7:正常":"GPIO6-7:異常","SW1:次へ");waitButton(KUMITATE_PIN_SW1);}
void FactoryTest::summary(){char a[32],b[24];snprintf(a,sizeof(a),"正常:%u 異常:%u",passCount,failCount);snprintf(b,sizeof(b),"省略:%u",skipCount);screen(failCount?"総合判定:異常":"総合判定:正常",a,b,"SW4:再検査");}
